# Generated by Django 4.2.24 on 2025-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favicon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
