# Generated by Django 4.2.24 on 2025-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favicon_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='favicon',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
